version: "3.8"
services:
  sources-oc:
    build:
      context: .
      target: dev
    env_file: .env
    networks:
      - elasticsearch
      - sources
    restart: on-failure
    volumes:
      - ./bin:/home/x/r/bin
      - ./config:/home/x/r/config
      - ./Gemfile.lock:/home/x/r/Gemfile.lock
      - ./Gemfile:/home/x/r/Gemfile
      - ./lib:/home/x/r/lib
      - ./register_sources_oc.gemspec:/home/x/r/register_sources_oc.gemspec
      - ./spec:/home/x/r/spec
networks:
  elasticsearch: {}
  sources: {}
